[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_20"]

[phases.install]
cmds = [
    "cd back_end && python3 -m pip install --no-cache-dir -r requirements.txt",
    "cd front_end && npm install"
]

[phases.build]
cmds = [
    "cd front_end && npm run build"
]

[start]
cmd = "bash start.sh"
